export enum RestaurantStatus {
  DRAFT = 'DRAFT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  ACTIVE = 'ACTIVE',
  CHANGES_REQUIRED = 'CHANGES_REQUIRED',
  REJECTED = 'REJECTED',
  BLOCKED = 'BLOCKED',
  ARCHIVED = 'ARCHIVED'
}
